'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SIGEBIBLIOTECA

    Partial Public Class Dashboard

        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents MenuLateral As Global.System.Web.UI.UserControl
        Protected WithEvents litEmprestimosAtivos As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents litDevolucoes As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents litReceitaTotal As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents litTotalLeitores As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents gvLeitoresFrequentes As Global.System.Web.UI.WebControls.GridView
        Protected WithEvents gvLivrosSolicitados As Global.System.Web.UI.WebControls.GridView
        Protected WithEvents litScriptGrafico As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace