'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SIGEBIBLIOTECA
    Partial Public Class MenuLateral
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents litNomeUsuario As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents phMenuAdmin As Global.System.Web.UI.WebControls.PlaceHolder
        Protected WithEvents phLogsAdmin As Global.System.Web.UI.WebControls.PlaceHolder
    End Class
End Namespace