'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SIGEBIBLIOTECA

    Partial Public Class Categorias

        '''<summary>
        '''Controle form1.
        '''</summary>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''Controle MenuLateral.
        '''</summary>
        '''Protected WithEvents MenuLateral As Global.SIGEBIBLIOTECA.MenuLateral

        '''<summary>
        '''Controle btnNovaCategoria.
        '''</summary>
        Protected WithEvents btnNovaCategoria As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Controle pnlAlerta.
        '''</summary>
        Protected WithEvents pnlAlerta As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Controle lblMensagemAlerta.
        '''</summary>
        Protected WithEvents lblMensagemAlerta As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Controle gvCategorias.
        '''</summary>
        Protected WithEvents gvCategorias As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''Controle litTituloModal.
        '''</summary>
        Protected WithEvents litTituloModal As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''Controle hfIdCategoria.
        '''</summary>
        Protected WithEvents hfIdCategoria As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''Controle txtNome.
        '''</summary>
        Protected WithEvents txtNome As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Controle txtDescricao.
        '''</summary>
        Protected WithEvents txtDescricao As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Controle btnSalvar.
        '''</summary>
        Protected WithEvents btnSalvar As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace