'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SIGEBIBLIOTECA

    Partial Public Class Emprestimos

        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
        Protected WithEvents btnNovoEmprestimo As Global.System.Web.UI.WebControls.Button
        Protected WithEvents pnlMensagem As Global.System.Web.UI.WebControls.Panel
        Protected WithEvents lblMensagem As Global.System.Web.UI.WebControls.Label
        Protected WithEvents gvEmprestimos As Global.System.Web.UI.WebControls.GridView

        ' Modal Novo Empréstimo
        Protected WithEvents pnlModalNovo As Global.System.Web.UI.WebControls.Panel
        Protected WithEvents btnCloseModalNovo As Global.System.Web.UI.WebControls.Button
        Protected WithEvents ddlLeitor As Global.System.Web.UI.WebControls.DropDownList
        Protected WithEvents ddlLivro As Global.System.Web.UI.WebControls.DropDownList
        Protected WithEvents txtDataPrevista As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtDiasPrevistos As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtPrecoDia As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents lblDescontoFidelidade As Global.System.Web.UI.WebControls.Label
        Protected WithEvents txtValorTotalEstimado As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtValor70 As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents btnCancelarNovo As Global.System.Web.UI.WebControls.Button
        Protected WithEvents btnSalvarEmprestimo As Global.System.Web.UI.WebControls.Button

        ' Modal Devolução
        Protected WithEvents pnlModalDevolucao As Global.System.Web.UI.WebControls.Panel
        Protected WithEvents btnCloseModalDevolucao As Global.System.Web.UI.WebControls.Button
        Protected WithEvents hfIdEmprestimoDevolucao As Global.System.Web.UI.WebControls.HiddenField
        Protected WithEvents lblDevLivro As Global.System.Web.UI.WebControls.Label
        Protected WithEvents lblDevLeitor As Global.System.Web.UI.WebControls.Label
        Protected WithEvents txtDataRealDevolucao As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents chkHouveDano As Global.System.Web.UI.WebControls.CheckBox
        Protected WithEvents txtSaldo30 As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtMultaAtraso As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtMultaDano As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtTotalDevolucao As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents btnCancelarDevolucao As Global.System.Web.UI.WebControls.Button
        Protected WithEvents btnConfirmarDevolucao As Global.System.Web.UI.WebControls.Button

        ' Modal Detalhes
        Protected WithEvents pnlModalDetalhes As Global.System.Web.UI.WebControls.Panel
        Protected WithEvents btnCloseModalDetalhes As Global.System.Web.UI.WebControls.Button
        Protected WithEvents litDetalhes As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents btnFecharDetalhes As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace