'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SIGEBIBLIOTECA

    Partial Public Class Leitores

        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
        Protected WithEvents MenuLateral As Global.System.Web.UI.UserControl
        Protected WithEvents btnNovoLeitor As Global.System.Web.UI.WebControls.Button
        Protected WithEvents pnlAlerta As Global.System.Web.UI.WebControls.Panel
        Protected WithEvents lblMensagemAlerta As Global.System.Web.UI.WebControls.Label
        Protected WithEvents gvLeitores As Global.System.Web.UI.WebControls.GridView
        Protected WithEvents litTituloModal As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents hfIdLeitor As Global.System.Web.UI.WebControls.HiddenField
        Protected WithEvents txtNome As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents ddlTipoLeitor As Global.System.Web.UI.WebControls.DropDownList
        Protected WithEvents txtTelefone As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtEndereco As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents pnlAcademico As Global.System.Web.UI.WebControls.Panel
        Protected WithEvents txtCurso As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtTurma As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents btnSalvar As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace