'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for recriado.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SIGEBIBLIOTECA

    Partial Public Class Livros

        '''<summary>
        '''Controle form1.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''Controle ScriptManager1.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''Controle MenuLateral.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents MenuLateral As Global.System.Web.UI.UserControl

        '''<summary>
        '''Controle btnNovoLivro.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents btnNovoLivro As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Controle pnlAlerta.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents pnlAlerta As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Controle lblMensagemAlerta.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents lblMensagemAlerta As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Controle gvLivros.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents gvLivros As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''Controle litTituloModal.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents litTituloModal As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''Controle hfIdLivro.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents hfIdLivro As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''Controle txtTitulo.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents txtTitulo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Controle ddlCategoria.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents ddlCategoria As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Controle txtAutor.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents txtAutor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Controle txtDesigner.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents txtDesigner As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Controle txtEditora.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents txtEditora As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Controle txtEdicao.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents txtEdicao As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Controle txtAnoPublicacao.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents txtAnoPublicacao As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Controle txtQtdTotal.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents txtQtdTotal As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Controle txtPrecoEmprestimoDia.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents txtPrecoEmprestimoDia As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Controle txtValorCompra.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents txtValorCompra As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Controle btnSalvar.
        '''</summary>
        '''<remarks>
        '''Campo gerado automaticamente.
        '''Para modificar, mova a declaração de campo do arquivo de designer para o arquivo code-behind.
        '''</remarks>
        Protected WithEvents btnSalvar As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace