'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SIGEBIBLIOTECA.views

    Partial Public Class Logs

        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
        Protected WithEvents MenuLateral As Global.System.Web.UI.UserControl
        Protected WithEvents upPrincipal As Global.System.Web.UI.UpdatePanel
        Protected WithEvents gvLogs As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace