'----------------'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SIGEBIBLIOTECA

    Partial Public Class Relatorios

        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents MenuLateral As Global.System.Web.UI.UserControl
        Protected WithEvents ddlTipoRelatorio As Global.System.Web.UI.WebControls.DropDownList
        Protected WithEvents txtDataInicio As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtDataFim As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtTermoBusca As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents btnFiltrar As Global.System.Web.UI.WebControls.Button
        Protected WithEvents btnExportarPDF As Global.System.Web.UI.WebControls.Button
        Protected WithEvents lblTotalRegistros As Global.System.Web.UI.WebControls.Label
        Protected WithEvents gvRelatorio As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace