'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SIGEBIBLIOTECA.views

    Partial Public Class Usuarios

        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
        Protected WithEvents MenuLateral As Global.System.Web.UI.UserControl
        Protected WithEvents btnNovoUsuario As Global.System.Web.UI.WebControls.Button
        Protected WithEvents upPrincipal As Global.System.Web.UI.UpdatePanel
        Protected WithEvents pnlAlerta As Global.System.Web.UI.WebControls.Panel
        Protected WithEvents lblMensagemAlerta As Global.System.Web.UI.WebControls.Label
        Protected WithEvents gvUsuarios As Global.System.Web.UI.WebControls.GridView
        Protected WithEvents litTituloModal As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents hfIdUsuario As Global.System.Web.UI.WebControls.HiddenField
        Protected WithEvents txtNome As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtSenha As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents ddlPerfil As Global.System.Web.UI.WebControls.DropDownList
        Protected WithEvents btnSalvarUsuario As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace